# version:     "0027--17-Sep-2022"
copyright: "2022"
author: "catherineeangel"
name: "Catherine Angel Robin"
title: "OS222: Operating Systems 2022-2"
githublink: "https://github.com/catherineeangel/os222"
myloglink: "/TXT/mylog.txt"
tarballlink: "https://os.vlsm.org/Log/catherineeangel.tar.bz2.txt"
encoding: UTF-8
markdown: kramdown
input: GFM
hard_wrap: false
github: [metadata]
